[2024-02-21T08:06:30.662+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-02T01:00:00+00:00 [queued]>
[2024-02-21T08:06:30.669+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-02T01:00:00+00:00 [queued]>
[2024-02-21T08:06:30.669+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T08:06:30.677+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-02-02 01:00:00+00:00
[2024-02-21T08:06:30.681+0000] {standard_task_runner.py:60} INFO - Started process 173 to run task
[2024-02-21T08:06:30.683+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-02-02T01:00:00+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpm8erycw5']
[2024-02-21T08:06:30.684+0000] {standard_task_runner.py:88} INFO - Job 185: Subtask get_mail
[2024-02-21T08:06:30.713+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-02-02T01:00:00+00:00 [running]> on host 96f19b77385b
[2024-02-21T08:06:30.766+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-02-02T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-02T01:00:00+00:00'
[2024-02-21T08:06:34.017+0000] {ImapSmtp.py:839} INFO - IMAP search: 'gmail:'Message from RPA Python' after:15-12-2023'
[2024-02-21T08:06:37.588+0000] {logging_mixin.py:188} INFO - Message from RPA Python0
[2024-02-21T08:06:37.589+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-156.txt')
[2024-02-21T08:06:37.590+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:37.590+0000] {logging_mixin.py:188} INFO - Message from RPA Python1
[2024-02-21T08:06:37.591+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-157.txt')
[2024-02-21T08:06:37.591+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:37.592+0000] {logging_mixin.py:188} INFO - Message from RPA Python2
[2024-02-21T08:06:37.592+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-158.txt')
[2024-02-21T08:06:37.593+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:37.593+0000] {logging_mixin.py:188} INFO - Message from RPA Python3
[2024-02-21T08:06:37.594+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-159.txt')
[2024-02-21T08:06:37.595+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:37.595+0000] {logging_mixin.py:188} INFO - Message from RPA Python4
[2024-02-21T08:06:37.596+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-160.txt')
[2024-02-21T08:06:37.596+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:37.596+0000] {logging_mixin.py:188} INFO - Message from RPA Python5
[2024-02-21T08:06:37.598+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-161.txt')
[2024-02-21T08:06:37.598+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:37.598+0000] {logging_mixin.py:188} INFO - Message from RPA Python6
[2024-02-21T08:06:37.599+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-162.txt')
[2024-02-21T08:06:37.599+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:37.599+0000] {logging_mixin.py:188} INFO - Message from RPA Python7
[2024-02-21T08:06:37.601+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-163.txt')
[2024-02-21T08:06:37.601+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:37.601+0000] {logging_mixin.py:188} INFO - Message from RPA Python8
[2024-02-21T08:06:37.602+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-164.txt')
[2024-02-21T08:06:37.602+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:37.602+0000] {logging_mixin.py:188} INFO - Message from RPA Python9
[2024-02-21T08:06:37.604+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-165.txt')
[2024-02-21T08:06:37.604+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:38.193+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-21T08:06:38.204+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=extract_email, task_id=get_mail, execution_date=20240202T010000, start_date=20240221T080630, end_date=20240221T080638
[2024-02-21T08:06:38.250+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-21T08:06:38.264+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-21T08:12:44.679+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-02T01:00:00+00:00 [queued]>
[2024-02-21T08:12:44.695+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-02T01:00:00+00:00 [queued]>
[2024-02-21T08:12:44.696+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T08:12:44.718+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-02-02 01:00:00+00:00
[2024-02-21T08:12:44.731+0000] {standard_task_runner.py:60} INFO - Started process 139 to run task
[2024-02-21T08:12:44.736+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-02-02T01:00:00+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpn8gnz1m5']
[2024-02-21T08:12:44.739+0000] {standard_task_runner.py:88} INFO - Job 216: Subtask get_mail
[2024-02-21T08:12:44.802+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-02-02T01:00:00+00:00 [running]> on host 968b17b6b013
[2024-02-21T08:12:44.914+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-02-02T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-02T01:00:00+00:00'
[2024-02-21T08:12:46.972+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_email.py", line 16, in get_mail
    mail.authorize(account=os.getenv("GMAIL_ACCOUNT"), password=os.getenv("GMAIL_PASSWORD"))
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 496, in authorize
    self.authorize_imap(
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 453, in authorize_imap
    self.imap_conn.login(account, password)
  File "/usr/local/lib/python3.8/imaplib.py", line 603, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Too many simultaneous connections. (Failure)'
[2024-02-21T08:12:46.989+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_email, task_id=get_mail, execution_date=20240202T010000, start_date=20240221T081244, end_date=20240221T081246
[2024-02-21T08:12:47.012+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 216 for task get_mail (b'[ALERT] Too many simultaneous connections. (Failure)'; 139)
[2024-02-21T08:12:47.043+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-21T08:12:47.063+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-21T08:17:45.227+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-02T01:00:00+00:00 [queued]>
[2024-02-21T08:17:45.250+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-02T01:00:00+00:00 [queued]>
[2024-02-21T08:17:45.250+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T08:17:45.284+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-02-02 01:00:00+00:00
[2024-02-21T08:17:45.296+0000] {standard_task_runner.py:60} INFO - Started process 88 to run task
[2024-02-21T08:17:45.319+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-02-02T01:00:00+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpa2uvoy95']
[2024-02-21T08:17:45.326+0000] {standard_task_runner.py:88} INFO - Job 248: Subtask get_mail
[2024-02-21T08:17:45.438+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-02-02T01:00:00+00:00 [running]> on host 9f5f399fdbe3
[2024-02-21T08:17:45.603+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-02-02T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-02T01:00:00+00:00'
[2024-02-21T08:17:48.088+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_email.py", line 16, in get_mail
    mail.authorize(account=os.getenv("GMAIL_ACCOUNT"), password=os.getenv("GMAIL_PASSWORD"))
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 496, in authorize
    self.authorize_imap(
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 453, in authorize_imap
    self.imap_conn.login(account, password)
  File "/usr/local/lib/python3.8/imaplib.py", line 603, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Too many simultaneous connections. (Failure)'
[2024-02-21T08:17:48.103+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_email, task_id=get_mail, execution_date=20240202T010000, start_date=20240221T081745, end_date=20240221T081748
[2024-02-21T08:17:48.123+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 248 for task get_mail (b'[ALERT] Too many simultaneous connections. (Failure)'; 88)
[2024-02-21T08:17:48.153+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-21T08:17:48.170+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
