[2024-02-21T08:06:14.795+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-21T01:00:00+00:00 [queued]>
[2024-02-21T08:06:14.806+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-21T01:00:00+00:00 [queued]>
[2024-02-21T08:06:14.807+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T08:06:14.818+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-01-21 01:00:00+00:00
[2024-02-21T08:06:14.823+0000] {standard_task_runner.py:60} INFO - Started process 131 to run task
[2024-02-21T08:06:14.825+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-01-21T01:00:00+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpemx7legf']
[2024-02-21T08:06:14.827+0000] {standard_task_runner.py:88} INFO - Job 167: Subtask get_mail
[2024-02-21T08:06:14.858+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-01-21T01:00:00+00:00 [running]> on host 96f19b77385b
[2024-02-21T08:06:14.925+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-01-21T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-21T01:00:00+00:00'
[2024-02-21T08:06:17.886+0000] {ImapSmtp.py:839} INFO - IMAP search: 'gmail:'Message from RPA Python' after:15-12-2023'
[2024-02-21T08:06:21.282+0000] {logging_mixin.py:188} INFO - Message from RPA Python0
[2024-02-21T08:06:21.287+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-81.txt')
[2024-02-21T08:06:21.287+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:21.288+0000] {logging_mixin.py:188} INFO - Message from RPA Python1
[2024-02-21T08:06:21.289+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-82.txt')
[2024-02-21T08:06:21.289+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:21.289+0000] {logging_mixin.py:188} INFO - Message from RPA Python2
[2024-02-21T08:06:21.290+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-83.txt')
[2024-02-21T08:06:21.290+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:21.291+0000] {logging_mixin.py:188} INFO - Message from RPA Python3
[2024-02-21T08:06:21.292+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-84.txt')
[2024-02-21T08:06:21.293+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:21.293+0000] {logging_mixin.py:188} INFO - Message from RPA Python4
[2024-02-21T08:06:21.296+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-85.txt')
[2024-02-21T08:06:21.297+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:21.297+0000] {logging_mixin.py:188} INFO - Message from RPA Python5
[2024-02-21T08:06:21.298+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-86.txt')
[2024-02-21T08:06:21.299+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:21.299+0000] {logging_mixin.py:188} INFO - Message from RPA Python6
[2024-02-21T08:06:21.300+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-87.txt')
[2024-02-21T08:06:21.301+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:21.301+0000] {logging_mixin.py:188} INFO - Message from RPA Python7
[2024-02-21T08:06:21.302+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-88.txt')
[2024-02-21T08:06:21.303+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:21.307+0000] {logging_mixin.py:188} INFO - Message from RPA Python8
[2024-02-21T08:06:21.308+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-89.txt')
[2024-02-21T08:06:21.308+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:21.309+0000] {logging_mixin.py:188} INFO - Message from RPA Python9
[2024-02-21T08:06:21.309+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-90.txt')
[2024-02-21T08:06:21.310+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:21.999+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-21T08:06:22.035+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=extract_email, task_id=get_mail, execution_date=20240121T010000, start_date=20240221T080614, end_date=20240221T080622
[2024-02-21T08:06:22.096+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-21T08:06:22.153+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-21T08:12:41.753+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-21T01:00:00+00:00 [queued]>
[2024-02-21T08:12:41.760+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-21T01:00:00+00:00 [queued]>
[2024-02-21T08:12:41.760+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T08:12:41.770+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-01-21 01:00:00+00:00
[2024-02-21T08:12:41.776+0000] {standard_task_runner.py:60} INFO - Started process 127 to run task
[2024-02-21T08:12:41.779+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-01-21T01:00:00+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpjopou2ni']
[2024-02-21T08:12:41.780+0000] {standard_task_runner.py:88} INFO - Job 204: Subtask get_mail
[2024-02-21T08:12:41.819+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-01-21T01:00:00+00:00 [running]> on host 968b17b6b013
[2024-02-21T08:12:41.875+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-01-21T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-21T01:00:00+00:00'
[2024-02-21T08:12:44.370+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_email.py", line 16, in get_mail
    mail.authorize(account=os.getenv("GMAIL_ACCOUNT"), password=os.getenv("GMAIL_PASSWORD"))
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 496, in authorize
    self.authorize_imap(
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 453, in authorize_imap
    self.imap_conn.login(account, password)
  File "/usr/local/lib/python3.8/imaplib.py", line 603, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Too many simultaneous connections. (Failure)'
[2024-02-21T08:12:44.383+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_email, task_id=get_mail, execution_date=20240121T010000, start_date=20240221T081241, end_date=20240221T081244
[2024-02-21T08:12:44.406+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 204 for task get_mail (b'[ALERT] Too many simultaneous connections. (Failure)'; 127)
[2024-02-21T08:12:44.449+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-21T08:12:44.471+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-21T08:17:43.105+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-21T01:00:00+00:00 [queued]>
[2024-02-21T08:17:43.115+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-21T01:00:00+00:00 [queued]>
[2024-02-21T08:17:43.115+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T08:17:43.127+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-01-21 01:00:00+00:00
[2024-02-21T08:17:43.132+0000] {standard_task_runner.py:60} INFO - Started process 76 to run task
[2024-02-21T08:17:43.134+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-01-21T01:00:00+00:00', '--job-id', '236', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpzivay10y']
[2024-02-21T08:17:43.136+0000] {standard_task_runner.py:88} INFO - Job 236: Subtask get_mail
[2024-02-21T08:17:43.167+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-01-21T01:00:00+00:00 [running]> on host 9f5f399fdbe3
[2024-02-21T08:17:43.221+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-01-21T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-21T01:00:00+00:00'
[2024-02-21T08:17:45.429+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_email.py", line 16, in get_mail
    mail.authorize(account=os.getenv("GMAIL_ACCOUNT"), password=os.getenv("GMAIL_PASSWORD"))
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 496, in authorize
    self.authorize_imap(
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 453, in authorize_imap
    self.imap_conn.login(account, password)
  File "/usr/local/lib/python3.8/imaplib.py", line 603, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Too many simultaneous connections. (Failure)'
[2024-02-21T08:17:45.457+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_email, task_id=get_mail, execution_date=20240121T010000, start_date=20240221T081743, end_date=20240221T081745
[2024-02-21T08:17:45.497+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 236 for task get_mail (b'[ALERT] Too many simultaneous connections. (Failure)'; 76)
[2024-02-21T08:17:45.531+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-21T08:17:45.554+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
