[2024-02-21T08:06:15.560+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-25T01:00:00+00:00 [queued]>
[2024-02-21T08:06:15.569+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-25T01:00:00+00:00 [queued]>
[2024-02-21T08:06:15.569+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T08:06:15.582+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-01-25 01:00:00+00:00
[2024-02-21T08:06:15.587+0000] {standard_task_runner.py:60} INFO - Started process 139 to run task
[2024-02-21T08:06:15.590+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-01-25T01:00:00+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmp_v9vleuf']
[2024-02-21T08:06:15.592+0000] {standard_task_runner.py:88} INFO - Job 175: Subtask get_mail
[2024-02-21T08:06:15.638+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-01-25T01:00:00+00:00 [running]> on host 96f19b77385b
[2024-02-21T08:06:15.707+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-01-25T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-25T01:00:00+00:00'
[2024-02-21T08:06:18.563+0000] {ImapSmtp.py:839} INFO - IMAP search: 'gmail:'Message from RPA Python' after:15-12-2023'
[2024-02-21T08:06:21.609+0000] {logging_mixin.py:188} INFO - Message from RPA Python0
[2024-02-21T08:06:21.611+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-91.txt')
[2024-02-21T08:06:21.611+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:21.613+0000] {logging_mixin.py:188} INFO - Message from RPA Python1
[2024-02-21T08:06:21.614+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-92.txt')
[2024-02-21T08:06:21.615+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:21.616+0000] {logging_mixin.py:188} INFO - Message from RPA Python2
[2024-02-21T08:06:21.618+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-93.txt')
[2024-02-21T08:06:21.618+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:21.619+0000] {logging_mixin.py:188} INFO - Message from RPA Python3
[2024-02-21T08:06:21.620+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-94.txt')
[2024-02-21T08:06:21.620+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:21.621+0000] {logging_mixin.py:188} INFO - Message from RPA Python4
[2024-02-21T08:06:21.622+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-95.txt')
[2024-02-21T08:06:21.623+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:21.625+0000] {logging_mixin.py:188} INFO - Message from RPA Python5
[2024-02-21T08:06:21.626+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-96.txt')
[2024-02-21T08:06:21.627+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:21.627+0000] {logging_mixin.py:188} INFO - Message from RPA Python6
[2024-02-21T08:06:21.629+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-97.txt')
[2024-02-21T08:06:21.629+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:21.630+0000] {logging_mixin.py:188} INFO - Message from RPA Python7
[2024-02-21T08:06:21.631+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-98.txt')
[2024-02-21T08:06:21.632+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:21.633+0000] {logging_mixin.py:188} INFO - Message from RPA Python8
[2024-02-21T08:06:21.635+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-99.txt')
[2024-02-21T08:06:21.636+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:21.636+0000] {logging_mixin.py:188} INFO - Message from RPA Python9
[2024-02-21T08:06:21.637+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-100.txt')
[2024-02-21T08:06:21.638+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:06:22.340+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-21T08:06:22.370+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=extract_email, task_id=get_mail, execution_date=20240125T010000, start_date=20240221T080615, end_date=20240221T080622
[2024-02-21T08:06:22.458+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-21T08:06:22.481+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-21T08:12:42.128+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-25T01:00:00+00:00 [queued]>
[2024-02-21T08:12:42.142+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-25T01:00:00+00:00 [queued]>
[2024-02-21T08:12:42.143+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T08:12:42.159+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-01-25 01:00:00+00:00
[2024-02-21T08:12:42.164+0000] {standard_task_runner.py:60} INFO - Started process 129 to run task
[2024-02-21T08:12:42.166+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-01-25T01:00:00+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpvq4e657n']
[2024-02-21T08:12:42.167+0000] {standard_task_runner.py:88} INFO - Job 206: Subtask get_mail
[2024-02-21T08:12:42.201+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-01-25T01:00:00+00:00 [running]> on host 968b17b6b013
[2024-02-21T08:12:42.253+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-01-25T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-25T01:00:00+00:00'
[2024-02-21T08:12:44.349+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_email.py", line 16, in get_mail
    mail.authorize(account=os.getenv("GMAIL_ACCOUNT"), password=os.getenv("GMAIL_PASSWORD"))
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 496, in authorize
    self.authorize_imap(
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 453, in authorize_imap
    self.imap_conn.login(account, password)
  File "/usr/local/lib/python3.8/imaplib.py", line 603, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Too many simultaneous connections. (Failure)'
[2024-02-21T08:12:44.363+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_email, task_id=get_mail, execution_date=20240125T010000, start_date=20240221T081242, end_date=20240221T081244
[2024-02-21T08:12:44.386+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 206 for task get_mail (b'[ALERT] Too many simultaneous connections. (Failure)'; 129)
[2024-02-21T08:12:44.431+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-21T08:12:44.453+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-21T08:17:44.022+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-25T01:00:00+00:00 [queued]>
[2024-02-21T08:17:44.032+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-01-25T01:00:00+00:00 [queued]>
[2024-02-21T08:17:44.032+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T08:17:44.044+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-01-25 01:00:00+00:00
[2024-02-21T08:17:44.050+0000] {standard_task_runner.py:60} INFO - Started process 79 to run task
[2024-02-21T08:17:44.053+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-01-25T01:00:00+00:00', '--job-id', '240', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpt1riupo3']
[2024-02-21T08:17:44.055+0000] {standard_task_runner.py:88} INFO - Job 240: Subtask get_mail
[2024-02-21T08:17:44.094+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-01-25T01:00:00+00:00 [running]> on host 9f5f399fdbe3
[2024-02-21T08:17:44.170+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-01-25T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-25T01:00:00+00:00'
[2024-02-21T08:17:46.833+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_email.py", line 16, in get_mail
    mail.authorize(account=os.getenv("GMAIL_ACCOUNT"), password=os.getenv("GMAIL_PASSWORD"))
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 496, in authorize
    self.authorize_imap(
  File "/home/airflow/.local/lib/python3.8/site-packages/RPA/Email/ImapSmtp.py", line 453, in authorize_imap
    self.imap_conn.login(account, password)
  File "/usr/local/lib/python3.8/imaplib.py", line 603, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[ALERT] Too many simultaneous connections. (Failure)'
[2024-02-21T08:17:46.846+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_email, task_id=get_mail, execution_date=20240125T010000, start_date=20240221T081744, end_date=20240221T081746
[2024-02-21T08:17:46.862+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 240 for task get_mail (b'[ALERT] Too many simultaneous connections. (Failure)'; 79)
[2024-02-21T08:17:46.892+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-21T08:17:46.908+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
